field: d7d77960-d953-455d-a7f9-28d6c6dfb833 # Inner Page Matrix
fieldLayouts:
  20ba744e-30ce-43a5-8bc0-72b58a685eca:
    tabs:
      -
        elements:
          -
            fieldUid: 8b8feb79-1046-4b14-9556-2eafb772496b # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8b8feb79-1046-4b14-9556-2eafb772496b: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '2'
      multiline: '1'
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: largeHeading
name: 'Large Heading'
sortOrder: 1
