field: d7d77960-d953-455d-a7f9-28d6c6dfb833 # Inner Page Matrix
fieldLayouts:
  336882f6-2187-4bac-903a-658ad9cf5bc3:
    tabs:
      -
        elements:
          -
            fieldUid: 3ae341fa-da25-437b-b723-1d467a54179e # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3ae341fa-da25-437b-b723-1d467a54179e: # Paragraph
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: ''
    name: Paragraph
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 2f10cfd8-276a-4b43-94ab-a677bad7010c
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Custom.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: paragraph
name: Paragraph
sortOrder: 3
