field: d7d77960-d953-455d-a7f9-28d6c6dfb833 # Inner Page Matrix
fieldLayouts:
  c64149d9-d728-4ed5-8282-2cb67b5fd372:
    tabs:
      -
        elements:
          -
            fieldUid: 375ad989-34bb-47bb-829c-b8fb8d4ab286 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d5f9b31e-340a-47b4-9324-8b6a19acbf5c # Paragraph
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  375ad989-34bb-47bb-829c-b8fb8d4ab286: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d5f9b31e-340a-47b4-9324-8b6a19acbf5c: # Paragraph
    contentColumnType: text
    fieldGroup: null
    handle: paragraph
    instructions: ''
    name: Paragraph
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes:
        - 2f10cfd8-276a-4b43-94ab-a677bad7010c
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: paragraphPrimaryBg
name: 'Paragraph Primary BG'
sortOrder: 4
