fieldLayouts:
  a58df3fd-f789-4791-a86d-b512d1b08b63:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: e530895c-6de1-4790-be9a-88222af380aa
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: c4f2730b-09bf-4dc1-a3f5-9a29df8ae72a
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 53919104-bd07-434f-9abc-39c6cfe7baf6
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Common
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d7d77960-d953-455d-a7f9-28d6c6dfb833 # Inner Page Matrix
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Inner Page'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 3e37a519-2497-4dbb-b7d0-78984beb23ae
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 2f290e8a-28e2-4cd9-a34a-48d4d48af0fc
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 0938e164-9146-4280-9720-237810b4b926
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d785d89a-bab0-42a6-ba07-2d62a9c31b53
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: 'Social Links'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 62caa9dc-1699-4df1-aede-d8715a247d78
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b15ca5cb-e30d-4fc3-b518-2c18dd66bb00
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e8a6d443-d5a6-47d6-b808-20286df833b6
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d7583edf-ba9b-4bd8-a32a-77ea7655ec8f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 4
handle: news
hasTitleField: true
name: News
section: 74b8edf4-0b21-40c0-b3d7-18ca19b1130d
sortOrder: 1
titleFormat: ''
