fieldLayouts:
  8d403ca8-9339-428d-b88c-a567df79cff3:
    tabs:
      -
        elements:
          -
            instructions: null
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 62caa9dc-1699-4df1-aede-d8715a247d78
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: b15ca5cb-e30d-4fc3-b518-2c18dd66bb00
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e8a6d443-d5a6-47d6-b808-20286df833b6
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: d7583edf-ba9b-4bd8-a32a-77ea7655ec8f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 1
handle: porcelainVeneersCrowns
hasTitleField: true
name: 'Porcelain Veneers & Crowns'
section: 14c1c108-18f6-4b52-946c-fe641b9fa0b1
sortOrder: 1
titleFormat: '{section.name|raw}'
