contentColumnType: string
fieldGroup: fa953446-323d-4ead-92ad-1dd0c77d9e8a
handle: backupImage
instructions: 'Image displayed when no image asset is selected'
name: 'Backup Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2f10cfd8-276a-4b43-94ab-a677bad7010c'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:2f10cfd8-276a-4b43-94ab-a677bad7010c'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
