contentColumnType: text
fieldGroup: 01f54834-a45f-4dcf-941f-c88597c01fa6
handle: locationShortStoreHours
instructions: 'Short line of text to describe store hours'
name: 'Location Short Store Hours'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
