contentColumnType: string
fieldGroup: bc981df3-8707-46cf-95ee-de00eaa31486
handle: mainImage
instructions: ''
name: 'Main Image'
searchable: true
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:2f10cfd8-276a-4b43-94ab-a677bad7010c'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: ''
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:2f10cfd8-276a-4b43-94ab-a677bad7010c'
  singleUploadLocationSubpath: ''
  source: null
  sources:
    - 'volume:2f10cfd8-276a-4b43-94ab-a677bad7010c'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
