contentColumnType: text
fieldGroup: ed5c5e6e-c7f2-4b48-95f9-c3095904c1f9
handle: seoPreview
instructions: ''
name: 'SEO Preview'
searchable: true
settings:
  elementDisplayPreviewType: google
  facebookEnabledFields:
    - seoPreview
  facebookTabEnabled: '1'
  generalEnabledFields:
    - seoPreview
  generalTabEnabled: '1'
  sitemapTabEnabled: ''
  twitterTabEnabled: ''
translationKeyFormat: null
translationMethod: none
type: nystudio107\seomatic\fields\SeoSettings
