contentColumnType: text
fieldGroup: ed5c5e6e-c7f2-4b48-95f9-c3095904c1f9
handle: seoTitle
instructions: ''
name: 'SEO Title'
searchable: true
settings:
  charLimit: ''
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
