enableVersioning: true
handle: mainPage
name: 'Main Page'
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  cc6fa99a-ca93-4981-b944-2d8003b95c5b:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
