enableVersioning: true
handle: newsIndex
name: 'News Index'
propagationMethod: all
siteSettings:
  cc6fa99a-ca93-4981-b944-2d8003b95c5b:
    enabledByDefault: true
    hasUrls: true
    template: news/index.twig
    uriFormat: news
type: single
