enableVersioning: true
handle: partners
name: Partners
propagationMethod: all
siteSettings:
  cc6fa99a-ca93-4981-b944-2d8003b95c5b:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: ''
type: channel
