enableVersioning: true
handle: porcelainVeneersCrowns
name: 'Porcelain Veneers & Crowns'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  cc6fa99a-ca93-4981-b944-2d8003b95c5b:
    enabledByDefault: true
    hasUrls: true
    template: porcelain-veneers-crowns/index
    uriFormat: porcelain-veneers-crowns
type: single
